import { AiFillHtml5 } from "react-icons/ai";
import { BsGit } from "react-icons/bs";
import { FaReact } from "react-icons/fa";
import {
  SiSass,
  SiCss3,
  SiTailwindcss,
  SiStyledcomponents,
  SiMui,
  SiJavascript,
  SiTypescript,
  SiRedux,
  SiVercel,
  SiNetlify,
  SiNpm,
  SiYarn,
} from "react-icons/si";
import { TbBrandFirebase } from "react-icons/tb";

export const home = [
  {
    name: "NEŞATHAN ÖZTÜRK",
    job: "A FRONTEND DEVELOPER.",
  },
];

export const projects = [
  {
    id: 1,
    title: "e-commerce",
    language: "JavaScript",
    fork: 0,
    star: 0,
    link: "https://github.com/nesathanozturk/e-commerce",
  },
  {
    id: 2,
    title: "findmovie-app",
    language: "JavaScript",
    fork: 0,
    star: 1,
    link: "https://github.com/nesathanozturk/findmovie-app",
  },
  {
    id: 3,
    title: "countries-app",
    language: "TypeScript",
    fork: 0,
    star: 0,
    link: "https://github.com/nesathanozturk/countries-app",
  },
  {
    id: 4,
    title: "personel-website",
    language: "JavaScript",
    fork: 0,
    star: 0,
    link: "https://github.com/nesathanozturk/personel-website",
  },
  {
    id: 5,
    title: "getir-clone",
    language: "JavaScript",
    fork: 0,
    star: 1,
    link: "https://github.com/nesathanozturk/getir-clone",
  },
  {
    id: 6,
    title: "crypto-tracker",
    language: "TypeScript",
    fork: 0,
    star: 0,
    link: "https://github.com/nesathanozturk/crypto-tracker",
  },
];

export const icons = [
  {
    id: 1,
    title: "HTML5",
    Element: <AiFillHtml5 />,
    size: 60,
    color: "text-red-600",
    name: "html5",
  },
  {
    id: 2,
    title: "CSS3",
    Element: <SiCss3 />,
    size: 50,
    color: "text-blue-600",
    padding: "pt-2",
    name: "css3",
  },
  {
    id: 3,
    title: "SASS",
    Element: <SiSass />,
    size: 50,
    color: "text-pink-600",
    padding: "pt-1",
    name: "sass",
  },
  {
    id: 4,
    title: "TailwindCSS",
    Element: <SiTailwindcss />,
    size: 50,
    color: "text-blue-500",
    padding: "pt-1",
    name: "tailwindcss",
  },
  {
    id: 5,
    title: "Styled Components",
    Element: <SiStyledcomponents />,
    size: 55,
    color: "text-purple-600",
    name: "styledcomponents",
  },
  {
    id: 6,
    title: "Material UI",
    Element: <SiMui />,
    size: 55,
    color: "text-blue-500",
    name: "mui",
  },
  {
    id: 7,
    title: "JavaScript",
    Element: <SiJavascript />,
    size: 50,
    color: "text-yellow-500",
    padding: "pt-1",
    name: "javascript",
  },
  {
    id: 8,
    title: "TypeScript",
    Element: <SiTypescript />,
    size: 50,
    color: "text-blue-600",
    padding: "pt-1",
    name: "typescript",
  },
  {
    id: 9,
    title: "React",
    Element: <FaReact />,
    size: 50,
    color: "text-blue-500",
    padding: "pt-1",
    name: "react",
  },
  {
    id: 10,
    title: "Redux",
    Element: <SiRedux />,
    size: 50,
    color: "text-purple-600",
    name: "redux",
  },
  {
    id: 11,
    title: "Firebase",
    Element: <TbBrandFirebase />,
    size: 50,
    color: "text-yellow-500",
    name: "firebase",
  },
  {
    id: 12,
    title: "Vercel",
    Element: <SiVercel />,
    size: 50,
    color: "dark:text-white",
    name: "vercel",
  },
  {
    id: 13,
    title: "Netlify",
    Element: <SiNetlify />,
    size: 50,
    color: "text-cyan-500",
    name: "netlify",
  },
  {
    id: 14,
    title: "npm",
    Element: <SiNpm />,
    size: 50,
    color: "dark:text-white",
    name: "npm",
  },
  {
    id: 15,
    title: "yarn",
    Element: <SiYarn />,
    size: 50,
    color: "text-blue-500",
    name: "yarn",
  },
  {
    id: 16,
    title: "Git",
    Element: <BsGit />,
    size: 50,
    color: "text-red-600",
    name: "git",
  },
];
